server:
  port: 8666
spring:
  application:
    name: spring-ai-test
  datasource:
    username: root
    password: 1
    url: jdbc:mysql://localhost:3306/springaitest?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            schema: classpath:/schema-mysql.sql
    deepseek:
      api-key: ${DEEP_SEEK_KEY}
      chat:
        options:
          model: deepseek-chat
          max-tokens: 1024 # 生成文本的最大长度
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:4b
#logging:
#  level:
#    org:
#      springframework:
#        ai:
#          chat:
#            client:
#              advisor: DEBUG